name: ci

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: |
          cargo build --release

      - uses: actions/upload-artifact@v3
        with:
          name: binary
          path: target/release/markdown-test-report
          if-no-files-found: error
