name: release

on:
  push:
    tags:
      - "v*"

jobs:

  ci:
    uses: ctron/markdown-test-report/.github/workflows/ci.yaml@main

  release:
    needs: [ ci ]
    runs-on: ubuntu-20.04
    steps:

      - uses: actions/download-artifact@v2
        with:
          name: binary
      - name: Display downloaded content
        run: ls -R
      - run: |
          Move on
