name: release

on:
  push:
    tags:
      - "v*"

jobs:

  ci:
    runs-on: ubuntu-20.04
    steps:
      - uses: ./.github/workflows/ci.yaml

  release:
    needs: [ ci ]
    runs-on: ubuntu-20.04
    steps:
      - run: |
          Move on
