name: release

on:
  push:
    tags:
      - "v*"

jobs:

  ci:
    uses: ctron/markdown-test-report/.github/workflows/ci.yaml@main

  release:
    needs: [ ci ]
    runs-on: ubuntu-20.04
    steps:
      - run: |
          Move on
